//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace CabinetMgr.Bll.UpdateServiceRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UpdateServiceSoap", Namespace="http://jhy.org/")]
    public partial class UpdateService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAppFileListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAppFileBaseOperationCompleted;
        
        private SoapAuthHeader soapAuthHeaderValueField;
        
        private System.Threading.SendOrPostCallback GetAppBindingOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateAppBindingOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateBindingStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAppUserInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateAppUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateAppUserInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteAppUserInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAppListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAppVersionInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAppInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateAppOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateAppInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteAppInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CalculateAppChecksumOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubmitUpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback PrepareUploadOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfirmUploadOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckAuthInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UpdateService() {
            this.Url = global::CabinetMgr.Bll.Properties.Settings.Default.CabinetBll_UpdateServiceRef_MainService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public SoapAuthHeader SoapAuthHeaderValue {
            get {
                return this.soapAuthHeaderValueField;
            }
            set {
                this.soapAuthHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAppFileListCompletedEventHandler GetAppFileListCompleted;
        
        /// <remarks/>
        public event GetAppFileBaseCompletedEventHandler GetAppFileBaseCompleted;
        
        /// <remarks/>
        public event GetAppBindingCompletedEventHandler GetAppBindingCompleted;
        
        /// <remarks/>
        public event CreateAppBindingCompletedEventHandler CreateAppBindingCompleted;
        
        /// <remarks/>
        public event UpdateBindingStatusCompletedEventHandler UpdateBindingStatusCompleted;
        
        /// <remarks/>
        public event GetUserListCompletedEventHandler GetUserListCompleted;
        
        /// <remarks/>
        public event GetAppUserInfoCompletedEventHandler GetAppUserInfoCompleted;
        
        /// <remarks/>
        public event CreateAppUserCompletedEventHandler CreateAppUserCompleted;
        
        /// <remarks/>
        public event UpdateAppUserInfoCompletedEventHandler UpdateAppUserInfoCompleted;
        
        /// <remarks/>
        public event DeleteAppUserInfoCompletedEventHandler DeleteAppUserInfoCompleted;
        
        /// <remarks/>
        public event GetAppListCompletedEventHandler GetAppListCompleted;
        
        /// <remarks/>
        public event GetAppVersionInfoCompletedEventHandler GetAppVersionInfoCompleted;
        
        /// <remarks/>
        public event GetAppInfoCompletedEventHandler GetAppInfoCompleted;
        
        /// <remarks/>
        public event CreateAppCompletedEventHandler CreateAppCompleted;
        
        /// <remarks/>
        public event UpdateAppInfoCompletedEventHandler UpdateAppInfoCompleted;
        
        /// <remarks/>
        public event DeleteAppInfoCompletedEventHandler DeleteAppInfoCompleted;
        
        /// <remarks/>
        public event CalculateAppChecksumCompletedEventHandler CalculateAppChecksumCompleted;
        
        /// <remarks/>
        public event SubmitUpdateCompletedEventHandler SubmitUpdateCompleted;
        
        /// <remarks/>
        public event UploadFileCompletedEventHandler UploadFileCompleted;
        
        /// <remarks/>
        public event PrepareUploadCompletedEventHandler PrepareUploadCompleted;
        
        /// <remarks/>
        public event ConfirmUploadCompletedEventHandler ConfirmUploadCompleted;
        
        /// <remarks/>
        public event CheckAuthInfoCompletedEventHandler CheckAuthInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jhy.org/GetAppFileList", RequestNamespace="http://jhy.org/", ResponseNamespace="http://jhy.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetAppFileList(string appId, string userId) {
            object[] results = this.Invoke("GetAppFileList", new object[] {
                        appId,
                        userId});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAppFileListAsync(string appId, string userId) {
            this.GetAppFileListAsync(appId, userId, null);
        }
        
        /// <remarks/>
        public void GetAppFileListAsync(string appId, string userId, object userState) {
            if ((this.GetAppFileListOperationCompleted == null)) {
                this.GetAppFileListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAppFileListOperationCompleted);
            }
            this.InvokeAsync("GetAppFileList", new object[] {
                        appId,
                        userId}, this.GetAppFileListOperationCompleted, userState);
        }
        
        private void OnGetAppFileListOperationCompleted(object arg) {
            if ((this.GetAppFileListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAppFileListCompleted(this, new GetAppFileListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jhy.org/GetAppFileBase", RequestNamespace="http://jhy.org/", ResponseNamespace="http://jhy.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetAppFileBase(string appId, string userId) {
            object[] results = this.Invoke("GetAppFileBase", new object[] {
                        appId,
                        userId});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAppFileBaseAsync(string appId, string userId) {
            this.GetAppFileBaseAsync(appId, userId, null);
        }
        
        /// <remarks/>
        public void GetAppFileBaseAsync(string appId, string userId, object userState) {
            if ((this.GetAppFileBaseOperationCompleted == null)) {
                this.GetAppFileBaseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAppFileBaseOperationCompleted);
            }
            this.InvokeAsync("GetAppFileBase", new object[] {
                        appId,
                        userId}, this.GetAppFileBaseOperationCompleted, userState);
        }
        
        private void OnGetAppFileBaseOperationCompleted(object arg) {
            if ((this.GetAppFileBaseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAppFileBaseCompleted(this, new GetAppFileBaseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SoapAuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jhy.org/GetAppBinding", RequestNamespace="http://jhy.org/", ResponseNamespace="http://jhy.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetAppBinding(string appId) {
            object[] results = this.Invoke("GetAppBinding", new object[] {
                        appId});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAppBindingAsync(string appId) {
            this.GetAppBindingAsync(appId, null);
        }
        
        /// <remarks/>
        public void GetAppBindingAsync(string appId, object userState) {
            if ((this.GetAppBindingOperationCompleted == null)) {
                this.GetAppBindingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAppBindingOperationCompleted);
            }
            this.InvokeAsync("GetAppBinding", new object[] {
                        appId}, this.GetAppBindingOperationCompleted, userState);
        }
        
        private void OnGetAppBindingOperationCompleted(object arg) {
            if ((this.GetAppBindingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAppBindingCompleted(this, new GetAppBindingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SoapAuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jhy.org/CreateAppBinding", RequestNamespace="http://jhy.org/", ResponseNamespace="http://jhy.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] CreateAppBinding(string appId, string userId) {
            object[] results = this.Invoke("CreateAppBinding", new object[] {
                        appId,
                        userId});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void CreateAppBindingAsync(string appId, string userId) {
            this.CreateAppBindingAsync(appId, userId, null);
        }
        
        /// <remarks/>
        public void CreateAppBindingAsync(string appId, string userId, object userState) {
            if ((this.CreateAppBindingOperationCompleted == null)) {
                this.CreateAppBindingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateAppBindingOperationCompleted);
            }
            this.InvokeAsync("CreateAppBinding", new object[] {
                        appId,
                        userId}, this.CreateAppBindingOperationCompleted, userState);
        }
        
        private void OnCreateAppBindingOperationCompleted(object arg) {
            if ((this.CreateAppBindingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateAppBindingCompleted(this, new CreateAppBindingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SoapAuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jhy.org/UpdateBindingStatus", RequestNamespace="http://jhy.org/", ResponseNamespace="http://jhy.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] UpdateBindingStatus(string appId, string userId, int status) {
            object[] results = this.Invoke("UpdateBindingStatus", new object[] {
                        appId,
                        userId,
                        status});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void UpdateBindingStatusAsync(string appId, string userId, int status) {
            this.UpdateBindingStatusAsync(appId, userId, status, null);
        }
        
        /// <remarks/>
        public void UpdateBindingStatusAsync(string appId, string userId, int status, object userState) {
            if ((this.UpdateBindingStatusOperationCompleted == null)) {
                this.UpdateBindingStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateBindingStatusOperationCompleted);
            }
            this.InvokeAsync("UpdateBindingStatus", new object[] {
                        appId,
                        userId,
                        status}, this.UpdateBindingStatusOperationCompleted, userState);
        }
        
        private void OnUpdateBindingStatusOperationCompleted(object arg) {
            if ((this.UpdateBindingStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateBindingStatusCompleted(this, new UpdateBindingStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SoapAuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jhy.org/GetUserList", RequestNamespace="http://jhy.org/", ResponseNamespace="http://jhy.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetUserList() {
            object[] results = this.Invoke("GetUserList", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUserListAsync() {
            this.GetUserListAsync(null);
        }
        
        /// <remarks/>
        public void GetUserListAsync(object userState) {
            if ((this.GetUserListOperationCompleted == null)) {
                this.GetUserListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserListOperationCompleted);
            }
            this.InvokeAsync("GetUserList", new object[0], this.GetUserListOperationCompleted, userState);
        }
        
        private void OnGetUserListOperationCompleted(object arg) {
            if ((this.GetUserListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserListCompleted(this, new GetUserListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SoapAuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jhy.org/GetAppUserInfo", RequestNamespace="http://jhy.org/", ResponseNamespace="http://jhy.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetAppUserInfo(string userId) {
            object[] results = this.Invoke("GetAppUserInfo", new object[] {
                        userId});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAppUserInfoAsync(string userId) {
            this.GetAppUserInfoAsync(userId, null);
        }
        
        /// <remarks/>
        public void GetAppUserInfoAsync(string userId, object userState) {
            if ((this.GetAppUserInfoOperationCompleted == null)) {
                this.GetAppUserInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAppUserInfoOperationCompleted);
            }
            this.InvokeAsync("GetAppUserInfo", new object[] {
                        userId}, this.GetAppUserInfoOperationCompleted, userState);
        }
        
        private void OnGetAppUserInfoOperationCompleted(object arg) {
            if ((this.GetAppUserInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAppUserInfoCompleted(this, new GetAppUserInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SoapAuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jhy.org/CreateAppUser", RequestNamespace="http://jhy.org/", ResponseNamespace="http://jhy.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] CreateAppUser(string userName, string userDesp) {
            object[] results = this.Invoke("CreateAppUser", new object[] {
                        userName,
                        userDesp});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void CreateAppUserAsync(string userName, string userDesp) {
            this.CreateAppUserAsync(userName, userDesp, null);
        }
        
        /// <remarks/>
        public void CreateAppUserAsync(string userName, string userDesp, object userState) {
            if ((this.CreateAppUserOperationCompleted == null)) {
                this.CreateAppUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateAppUserOperationCompleted);
            }
            this.InvokeAsync("CreateAppUser", new object[] {
                        userName,
                        userDesp}, this.CreateAppUserOperationCompleted, userState);
        }
        
        private void OnCreateAppUserOperationCompleted(object arg) {
            if ((this.CreateAppUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateAppUserCompleted(this, new CreateAppUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SoapAuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jhy.org/UpdateAppUserInfo", RequestNamespace="http://jhy.org/", ResponseNamespace="http://jhy.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] UpdateAppUserInfo(string userId, string userName, string userDesp) {
            object[] results = this.Invoke("UpdateAppUserInfo", new object[] {
                        userId,
                        userName,
                        userDesp});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAppUserInfoAsync(string userId, string userName, string userDesp) {
            this.UpdateAppUserInfoAsync(userId, userName, userDesp, null);
        }
        
        /// <remarks/>
        public void UpdateAppUserInfoAsync(string userId, string userName, string userDesp, object userState) {
            if ((this.UpdateAppUserInfoOperationCompleted == null)) {
                this.UpdateAppUserInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateAppUserInfoOperationCompleted);
            }
            this.InvokeAsync("UpdateAppUserInfo", new object[] {
                        userId,
                        userName,
                        userDesp}, this.UpdateAppUserInfoOperationCompleted, userState);
        }
        
        private void OnUpdateAppUserInfoOperationCompleted(object arg) {
            if ((this.UpdateAppUserInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateAppUserInfoCompleted(this, new UpdateAppUserInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SoapAuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jhy.org/DeleteAppUserInfo", RequestNamespace="http://jhy.org/", ResponseNamespace="http://jhy.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] DeleteAppUserInfo(string userId) {
            object[] results = this.Invoke("DeleteAppUserInfo", new object[] {
                        userId});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void DeleteAppUserInfoAsync(string userId) {
            this.DeleteAppUserInfoAsync(userId, null);
        }
        
        /// <remarks/>
        public void DeleteAppUserInfoAsync(string userId, object userState) {
            if ((this.DeleteAppUserInfoOperationCompleted == null)) {
                this.DeleteAppUserInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteAppUserInfoOperationCompleted);
            }
            this.InvokeAsync("DeleteAppUserInfo", new object[] {
                        userId}, this.DeleteAppUserInfoOperationCompleted, userState);
        }
        
        private void OnDeleteAppUserInfoOperationCompleted(object arg) {
            if ((this.DeleteAppUserInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteAppUserInfoCompleted(this, new DeleteAppUserInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SoapAuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jhy.org/GetAppList", RequestNamespace="http://jhy.org/", ResponseNamespace="http://jhy.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetAppList() {
            object[] results = this.Invoke("GetAppList", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAppListAsync() {
            this.GetAppListAsync(null);
        }
        
        /// <remarks/>
        public void GetAppListAsync(object userState) {
            if ((this.GetAppListOperationCompleted == null)) {
                this.GetAppListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAppListOperationCompleted);
            }
            this.InvokeAsync("GetAppList", new object[0], this.GetAppListOperationCompleted, userState);
        }
        
        private void OnGetAppListOperationCompleted(object arg) {
            if ((this.GetAppListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAppListCompleted(this, new GetAppListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jhy.org/GetAppVersionInfo", RequestNamespace="http://jhy.org/", ResponseNamespace="http://jhy.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetAppVersionInfo(string appId, string userId) {
            object[] results = this.Invoke("GetAppVersionInfo", new object[] {
                        appId,
                        userId});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAppVersionInfoAsync(string appId, string userId) {
            this.GetAppVersionInfoAsync(appId, userId, null);
        }
        
        /// <remarks/>
        public void GetAppVersionInfoAsync(string appId, string userId, object userState) {
            if ((this.GetAppVersionInfoOperationCompleted == null)) {
                this.GetAppVersionInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAppVersionInfoOperationCompleted);
            }
            this.InvokeAsync("GetAppVersionInfo", new object[] {
                        appId,
                        userId}, this.GetAppVersionInfoOperationCompleted, userState);
        }
        
        private void OnGetAppVersionInfoOperationCompleted(object arg) {
            if ((this.GetAppVersionInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAppVersionInfoCompleted(this, new GetAppVersionInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jhy.org/GetAppInfo", RequestNamespace="http://jhy.org/", ResponseNamespace="http://jhy.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetAppInfo(string appId) {
            object[] results = this.Invoke("GetAppInfo", new object[] {
                        appId});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAppInfoAsync(string appId) {
            this.GetAppInfoAsync(appId, null);
        }
        
        /// <remarks/>
        public void GetAppInfoAsync(string appId, object userState) {
            if ((this.GetAppInfoOperationCompleted == null)) {
                this.GetAppInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAppInfoOperationCompleted);
            }
            this.InvokeAsync("GetAppInfo", new object[] {
                        appId}, this.GetAppInfoOperationCompleted, userState);
        }
        
        private void OnGetAppInfoOperationCompleted(object arg) {
            if ((this.GetAppInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAppInfoCompleted(this, new GetAppInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SoapAuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jhy.org/CreateApp", RequestNamespace="http://jhy.org/", ResponseNamespace="http://jhy.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] CreateApp(string appName, int appType) {
            object[] results = this.Invoke("CreateApp", new object[] {
                        appName,
                        appType});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void CreateAppAsync(string appName, int appType) {
            this.CreateAppAsync(appName, appType, null);
        }
        
        /// <remarks/>
        public void CreateAppAsync(string appName, int appType, object userState) {
            if ((this.CreateAppOperationCompleted == null)) {
                this.CreateAppOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateAppOperationCompleted);
            }
            this.InvokeAsync("CreateApp", new object[] {
                        appName,
                        appType}, this.CreateAppOperationCompleted, userState);
        }
        
        private void OnCreateAppOperationCompleted(object arg) {
            if ((this.CreateAppCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateAppCompleted(this, new CreateAppCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SoapAuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jhy.org/UpdateAppInfo", RequestNamespace="http://jhy.org/", ResponseNamespace="http://jhy.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] UpdateAppInfo(string appId, string appName) {
            object[] results = this.Invoke("UpdateAppInfo", new object[] {
                        appId,
                        appName});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAppInfoAsync(string appId, string appName) {
            this.UpdateAppInfoAsync(appId, appName, null);
        }
        
        /// <remarks/>
        public void UpdateAppInfoAsync(string appId, string appName, object userState) {
            if ((this.UpdateAppInfoOperationCompleted == null)) {
                this.UpdateAppInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateAppInfoOperationCompleted);
            }
            this.InvokeAsync("UpdateAppInfo", new object[] {
                        appId,
                        appName}, this.UpdateAppInfoOperationCompleted, userState);
        }
        
        private void OnUpdateAppInfoOperationCompleted(object arg) {
            if ((this.UpdateAppInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateAppInfoCompleted(this, new UpdateAppInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SoapAuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jhy.org/DeleteAppInfo", RequestNamespace="http://jhy.org/", ResponseNamespace="http://jhy.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] DeleteAppInfo(string appId) {
            object[] results = this.Invoke("DeleteAppInfo", new object[] {
                        appId});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void DeleteAppInfoAsync(string appId) {
            this.DeleteAppInfoAsync(appId, null);
        }
        
        /// <remarks/>
        public void DeleteAppInfoAsync(string appId, object userState) {
            if ((this.DeleteAppInfoOperationCompleted == null)) {
                this.DeleteAppInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteAppInfoOperationCompleted);
            }
            this.InvokeAsync("DeleteAppInfo", new object[] {
                        appId}, this.DeleteAppInfoOperationCompleted, userState);
        }
        
        private void OnDeleteAppInfoOperationCompleted(object arg) {
            if ((this.DeleteAppInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteAppInfoCompleted(this, new DeleteAppInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SoapAuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jhy.org/CalculateAppChecksum", RequestNamespace="http://jhy.org/", ResponseNamespace="http://jhy.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] CalculateAppChecksum(string appId, string appVersion) {
            object[] results = this.Invoke("CalculateAppChecksum", new object[] {
                        appId,
                        appVersion});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void CalculateAppChecksumAsync(string appId, string appVersion) {
            this.CalculateAppChecksumAsync(appId, appVersion, null);
        }
        
        /// <remarks/>
        public void CalculateAppChecksumAsync(string appId, string appVersion, object userState) {
            if ((this.CalculateAppChecksumOperationCompleted == null)) {
                this.CalculateAppChecksumOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalculateAppChecksumOperationCompleted);
            }
            this.InvokeAsync("CalculateAppChecksum", new object[] {
                        appId,
                        appVersion}, this.CalculateAppChecksumOperationCompleted, userState);
        }
        
        private void OnCalculateAppChecksumOperationCompleted(object arg) {
            if ((this.CalculateAppChecksumCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CalculateAppChecksumCompleted(this, new CalculateAppChecksumCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SoapAuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jhy.org/SubmitUpdate", RequestNamespace="http://jhy.org/", ResponseNamespace="http://jhy.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] SubmitUpdate(string appId, string appVersion, string[] userList, string changeLog) {
            object[] results = this.Invoke("SubmitUpdate", new object[] {
                        appId,
                        appVersion,
                        userList,
                        changeLog});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void SubmitUpdateAsync(string appId, string appVersion, string[] userList, string changeLog) {
            this.SubmitUpdateAsync(appId, appVersion, userList, changeLog, null);
        }
        
        /// <remarks/>
        public void SubmitUpdateAsync(string appId, string appVersion, string[] userList, string changeLog, object userState) {
            if ((this.SubmitUpdateOperationCompleted == null)) {
                this.SubmitUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitUpdateOperationCompleted);
            }
            this.InvokeAsync("SubmitUpdate", new object[] {
                        appId,
                        appVersion,
                        userList,
                        changeLog}, this.SubmitUpdateOperationCompleted, userState);
        }
        
        private void OnSubmitUpdateOperationCompleted(object arg) {
            if ((this.SubmitUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitUpdateCompleted(this, new SubmitUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SoapAuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jhy.org/UploadFile", RequestNamespace="http://jhy.org/", ResponseNamespace="http://jhy.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] UploadFile(string appId, string appVersion, string fileName, string encodedContent) {
            object[] results = this.Invoke("UploadFile", new object[] {
                        appId,
                        appVersion,
                        fileName,
                        encodedContent});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void UploadFileAsync(string appId, string appVersion, string fileName, string encodedContent) {
            this.UploadFileAsync(appId, appVersion, fileName, encodedContent, null);
        }
        
        /// <remarks/>
        public void UploadFileAsync(string appId, string appVersion, string fileName, string encodedContent, object userState) {
            if ((this.UploadFileOperationCompleted == null)) {
                this.UploadFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadFileOperationCompleted);
            }
            this.InvokeAsync("UploadFile", new object[] {
                        appId,
                        appVersion,
                        fileName,
                        encodedContent}, this.UploadFileOperationCompleted, userState);
        }
        
        private void OnUploadFileOperationCompleted(object arg) {
            if ((this.UploadFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadFileCompleted(this, new UploadFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SoapAuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jhy.org/PrepareUpload", RequestNamespace="http://jhy.org/", ResponseNamespace="http://jhy.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] PrepareUpload(string appId, string appVersion) {
            object[] results = this.Invoke("PrepareUpload", new object[] {
                        appId,
                        appVersion});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void PrepareUploadAsync(string appId, string appVersion) {
            this.PrepareUploadAsync(appId, appVersion, null);
        }
        
        /// <remarks/>
        public void PrepareUploadAsync(string appId, string appVersion, object userState) {
            if ((this.PrepareUploadOperationCompleted == null)) {
                this.PrepareUploadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPrepareUploadOperationCompleted);
            }
            this.InvokeAsync("PrepareUpload", new object[] {
                        appId,
                        appVersion}, this.PrepareUploadOperationCompleted, userState);
        }
        
        private void OnPrepareUploadOperationCompleted(object arg) {
            if ((this.PrepareUploadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PrepareUploadCompleted(this, new PrepareUploadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SoapAuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jhy.org/ConfirmUpload", RequestNamespace="http://jhy.org/", ResponseNamespace="http://jhy.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] ConfirmUpload(string appId, string appVersion) {
            object[] results = this.Invoke("ConfirmUpload", new object[] {
                        appId,
                        appVersion});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ConfirmUploadAsync(string appId, string appVersion) {
            this.ConfirmUploadAsync(appId, appVersion, null);
        }
        
        /// <remarks/>
        public void ConfirmUploadAsync(string appId, string appVersion, object userState) {
            if ((this.ConfirmUploadOperationCompleted == null)) {
                this.ConfirmUploadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmUploadOperationCompleted);
            }
            this.InvokeAsync("ConfirmUpload", new object[] {
                        appId,
                        appVersion}, this.ConfirmUploadOperationCompleted, userState);
        }
        
        private void OnConfirmUploadOperationCompleted(object arg) {
            if ((this.ConfirmUploadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmUploadCompleted(this, new ConfirmUploadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jhy.org/CheckAuthInfo", RequestNamespace="http://jhy.org/", ResponseNamespace="http://jhy.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] CheckAuthInfo(string userName, string password) {
            object[] results = this.Invoke("CheckAuthInfo", new object[] {
                        userName,
                        password});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void CheckAuthInfoAsync(string userName, string password) {
            this.CheckAuthInfoAsync(userName, password, null);
        }
        
        /// <remarks/>
        public void CheckAuthInfoAsync(string userName, string password, object userState) {
            if ((this.CheckAuthInfoOperationCompleted == null)) {
                this.CheckAuthInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckAuthInfoOperationCompleted);
            }
            this.InvokeAsync("CheckAuthInfo", new object[] {
                        userName,
                        password}, this.CheckAuthInfoOperationCompleted, userState);
        }
        
        private void OnCheckAuthInfoOperationCompleted(object arg) {
            if ((this.CheckAuthInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckAuthInfoCompleted(this, new CheckAuthInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jhy.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://jhy.org/", IsNullable=false)]
    public partial class SoapAuthHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetAppFileListCompletedEventHandler(object sender, GetAppFileListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAppFileListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAppFileListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetAppFileBaseCompletedEventHandler(object sender, GetAppFileBaseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAppFileBaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAppFileBaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetAppBindingCompletedEventHandler(object sender, GetAppBindingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAppBindingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAppBindingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CreateAppBindingCompletedEventHandler(object sender, CreateAppBindingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateAppBindingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateAppBindingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UpdateBindingStatusCompletedEventHandler(object sender, UpdateBindingStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateBindingStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateBindingStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetUserListCompletedEventHandler(object sender, GetUserListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetAppUserInfoCompletedEventHandler(object sender, GetAppUserInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAppUserInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAppUserInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CreateAppUserCompletedEventHandler(object sender, CreateAppUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateAppUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateAppUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UpdateAppUserInfoCompletedEventHandler(object sender, UpdateAppUserInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateAppUserInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateAppUserInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DeleteAppUserInfoCompletedEventHandler(object sender, DeleteAppUserInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteAppUserInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteAppUserInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetAppListCompletedEventHandler(object sender, GetAppListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAppListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAppListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetAppVersionInfoCompletedEventHandler(object sender, GetAppVersionInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAppVersionInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAppVersionInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetAppInfoCompletedEventHandler(object sender, GetAppInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAppInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAppInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CreateAppCompletedEventHandler(object sender, CreateAppCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateAppCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateAppCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UpdateAppInfoCompletedEventHandler(object sender, UpdateAppInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateAppInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateAppInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DeleteAppInfoCompletedEventHandler(object sender, DeleteAppInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteAppInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteAppInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CalculateAppChecksumCompletedEventHandler(object sender, CalculateAppChecksumCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CalculateAppChecksumCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CalculateAppChecksumCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SubmitUpdateCompletedEventHandler(object sender, SubmitUpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UploadFileCompletedEventHandler(object sender, UploadFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void PrepareUploadCompletedEventHandler(object sender, PrepareUploadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PrepareUploadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PrepareUploadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ConfirmUploadCompletedEventHandler(object sender, ConfirmUploadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmUploadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfirmUploadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CheckAuthInfoCompletedEventHandler(object sender, CheckAuthInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckAuthInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckAuthInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591