//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 

using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

#pragma warning disable 1591

namespace CabinetMgr.Updater.Web_References.UpdaterServiceRef {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [WebServiceBinding(Name="MainServiceSoap", Namespace="http://jhy.org/")]
    public partial class MainService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAllUnitOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAvailableUnitOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAppByUnitOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAvailableAppByUnitOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetServerVersionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFileUpdListOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReqFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReqFileUrlOperationCompleted;
        
        private System.Threading.SendOrPostCallback DelAppFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddAppOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenUpdateInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MainService() {
            this.Url = global::CabinetMgr.Updater.Properties.Settings.Default.CabinetMgrUpdater_UpdaterServiceRef_MainService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAllUnitCompletedEventHandler GetAllUnitCompleted;
        
        /// <remarks/>
        public event GetAvailableUnitCompletedEventHandler GetAvailableUnitCompleted;
        
        /// <remarks/>
        public event GetAppByUnitCompletedEventHandler GetAppByUnitCompleted;
        
        /// <remarks/>
        public event GetAvailableAppByUnitCompletedEventHandler GetAvailableAppByUnitCompleted;
        
        /// <remarks/>
        public event GetServerVersionCompletedEventHandler GetServerVersionCompleted;
        
        /// <remarks/>
        public event GetFileUpdListCompletedEventHandler GetFileUpdListCompleted;
        
        /// <remarks/>
        public event ReqFileCompletedEventHandler ReqFileCompleted;
        
        /// <remarks/>
        public event ReqFileUrlCompletedEventHandler ReqFileUrlCompleted;
        
        /// <remarks/>
        public event DelAppFileCompletedEventHandler DelAppFileCompleted;
        
        /// <remarks/>
        public event AddAppCompletedEventHandler AddAppCompleted;
        
        /// <remarks/>
        public event GenUpdateInfoCompletedEventHandler GenUpdateInfoCompleted;
        
        /// <remarks/>
        [SoapDocumentMethod("http://jhy.org/GetAllUnit", RequestNamespace="http://jhy.org/", ResponseNamespace="http://jhy.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetAllUnit() {
            object[] results = this.Invoke("GetAllUnit", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllUnitAsync() {
            this.GetAllUnitAsync(null);
        }
        
        /// <remarks/>
        public void GetAllUnitAsync(object userState) {
            if ((this.GetAllUnitOperationCompleted == null)) {
                this.GetAllUnitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllUnitOperationCompleted);
            }
            this.InvokeAsync("GetAllUnit", new object[0], this.GetAllUnitOperationCompleted, userState);
        }
        
        private void OnGetAllUnitOperationCompleted(object arg) {
            if ((this.GetAllUnitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllUnitCompleted(this, new GetAllUnitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://jhy.org/GetAvailableUnit", RequestNamespace="http://jhy.org/", ResponseNamespace="http://jhy.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetAvailableUnit(string author) {
            object[] results = this.Invoke("GetAvailableUnit", new object[] {
                        author});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetAvailableUnitAsync(string author) {
            this.GetAvailableUnitAsync(author, null);
        }
        
        /// <remarks/>
        public void GetAvailableUnitAsync(string author, object userState) {
            if ((this.GetAvailableUnitOperationCompleted == null)) {
                this.GetAvailableUnitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAvailableUnitOperationCompleted);
            }
            this.InvokeAsync("GetAvailableUnit", new object[] {
                        author}, this.GetAvailableUnitOperationCompleted, userState);
        }
        
        private void OnGetAvailableUnitOperationCompleted(object arg) {
            if ((this.GetAvailableUnitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAvailableUnitCompleted(this, new GetAvailableUnitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://jhy.org/GetAppByUnit", RequestNamespace="http://jhy.org/", ResponseNamespace="http://jhy.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetAppByUnit(string Unit) {
            object[] results = this.Invoke("GetAppByUnit", new object[] {
                        Unit});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetAppByUnitAsync(string Unit) {
            this.GetAppByUnitAsync(Unit, null);
        }
        
        /// <remarks/>
        public void GetAppByUnitAsync(string Unit, object userState) {
            if ((this.GetAppByUnitOperationCompleted == null)) {
                this.GetAppByUnitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAppByUnitOperationCompleted);
            }
            this.InvokeAsync("GetAppByUnit", new object[] {
                        Unit}, this.GetAppByUnitOperationCompleted, userState);
        }
        
        private void OnGetAppByUnitOperationCompleted(object arg) {
            if ((this.GetAppByUnitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAppByUnitCompleted(this, new GetAppByUnitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://jhy.org/GetAvailableAppByUnit", RequestNamespace="http://jhy.org/", ResponseNamespace="http://jhy.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetAvailableAppByUnit(string Unit, string author) {
            object[] results = this.Invoke("GetAvailableAppByUnit", new object[] {
                        Unit,
                        author});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetAvailableAppByUnitAsync(string Unit, string author) {
            this.GetAvailableAppByUnitAsync(Unit, author, null);
        }
        
        /// <remarks/>
        public void GetAvailableAppByUnitAsync(string Unit, string author, object userState) {
            if ((this.GetAvailableAppByUnitOperationCompleted == null)) {
                this.GetAvailableAppByUnitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAvailableAppByUnitOperationCompleted);
            }
            this.InvokeAsync("GetAvailableAppByUnit", new object[] {
                        Unit,
                        author}, this.GetAvailableAppByUnitOperationCompleted, userState);
        }
        
        private void OnGetAvailableAppByUnitOperationCompleted(object arg) {
            if ((this.GetAvailableAppByUnitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAvailableAppByUnitCompleted(this, new GetAvailableAppByUnitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://jhy.org/GetServerVersion", RequestNamespace="http://jhy.org/", ResponseNamespace="http://jhy.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetServerVersion(string AppName, string Unit) {
            object[] results = this.Invoke("GetServerVersion", new object[] {
                        AppName,
                        Unit});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetServerVersionAsync(string AppName, string Unit) {
            this.GetServerVersionAsync(AppName, Unit, null);
        }
        
        /// <remarks/>
        public void GetServerVersionAsync(string AppName, string Unit, object userState) {
            if ((this.GetServerVersionOperationCompleted == null)) {
                this.GetServerVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetServerVersionOperationCompleted);
            }
            this.InvokeAsync("GetServerVersion", new object[] {
                        AppName,
                        Unit}, this.GetServerVersionOperationCompleted, userState);
        }
        
        private void OnGetServerVersionOperationCompleted(object arg) {
            if ((this.GetServerVersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetServerVersionCompleted(this, new GetServerVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://jhy.org/GetFileUpdList", RequestNamespace="http://jhy.org/", ResponseNamespace="http://jhy.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetFileUpdList(string AppName, string Unit) {
            object[] results = this.Invoke("GetFileUpdList", new object[] {
                        AppName,
                        Unit});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetFileUpdListAsync(string AppName, string Unit) {
            this.GetFileUpdListAsync(AppName, Unit, null);
        }
        
        /// <remarks/>
        public void GetFileUpdListAsync(string AppName, string Unit, object userState) {
            if ((this.GetFileUpdListOperationCompleted == null)) {
                this.GetFileUpdListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFileUpdListOperationCompleted);
            }
            this.InvokeAsync("GetFileUpdList", new object[] {
                        AppName,
                        Unit}, this.GetFileUpdListOperationCompleted, userState);
        }
        
        private void OnGetFileUpdListOperationCompleted(object arg) {
            if ((this.GetFileUpdListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFileUpdListCompleted(this, new GetFileUpdListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://jhy.org/ReqFile", RequestNamespace="http://jhy.org/", ResponseNamespace="http://jhy.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: XmlElement(DataType="base64Binary")]
        public byte[] ReqFile(string Unit, string AppName, int ReqType, string FileName) {
            object[] results = this.Invoke("ReqFile", new object[] {
                        Unit,
                        AppName,
                        ReqType,
                        FileName});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void ReqFileAsync(string Unit, string AppName, int ReqType, string FileName) {
            this.ReqFileAsync(Unit, AppName, ReqType, FileName, null);
        }
        
        /// <remarks/>
        public void ReqFileAsync(string Unit, string AppName, int ReqType, string FileName, object userState) {
            if ((this.ReqFileOperationCompleted == null)) {
                this.ReqFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReqFileOperationCompleted);
            }
            this.InvokeAsync("ReqFile", new object[] {
                        Unit,
                        AppName,
                        ReqType,
                        FileName}, this.ReqFileOperationCompleted, userState);
        }
        
        private void OnReqFileOperationCompleted(object arg) {
            if ((this.ReqFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReqFileCompleted(this, new ReqFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://jhy.org/ReqFileUrl", RequestNamespace="http://jhy.org/", ResponseNamespace="http://jhy.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ReqFileUrl(string Unit, string AppName, int ReqType, string FileName) {
            object[] results = this.Invoke("ReqFileUrl", new object[] {
                        Unit,
                        AppName,
                        ReqType,
                        FileName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReqFileUrlAsync(string Unit, string AppName, int ReqType, string FileName) {
            this.ReqFileUrlAsync(Unit, AppName, ReqType, FileName, null);
        }
        
        /// <remarks/>
        public void ReqFileUrlAsync(string Unit, string AppName, int ReqType, string FileName, object userState) {
            if ((this.ReqFileUrlOperationCompleted == null)) {
                this.ReqFileUrlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReqFileUrlOperationCompleted);
            }
            this.InvokeAsync("ReqFileUrl", new object[] {
                        Unit,
                        AppName,
                        ReqType,
                        FileName}, this.ReqFileUrlOperationCompleted, userState);
        }
        
        private void OnReqFileUrlOperationCompleted(object arg) {
            if ((this.ReqFileUrlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReqFileUrlCompleted(this, new ReqFileUrlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://jhy.org/DelAppFile", RequestNamespace="http://jhy.org/", ResponseNamespace="http://jhy.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int DelAppFile(string Unit, string AppName) {
            object[] results = this.Invoke("DelAppFile", new object[] {
                        Unit,
                        AppName});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void DelAppFileAsync(string Unit, string AppName) {
            this.DelAppFileAsync(Unit, AppName, null);
        }
        
        /// <remarks/>
        public void DelAppFileAsync(string Unit, string AppName, object userState) {
            if ((this.DelAppFileOperationCompleted == null)) {
                this.DelAppFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelAppFileOperationCompleted);
            }
            this.InvokeAsync("DelAppFile", new object[] {
                        Unit,
                        AppName}, this.DelAppFileOperationCompleted, userState);
        }
        
        private void OnDelAppFileOperationCompleted(object arg) {
            if ((this.DelAppFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DelAppFileCompleted(this, new DelAppFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://jhy.org/AddApp", RequestNamespace="http://jhy.org/", ResponseNamespace="http://jhy.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AddApp(string AppName, string Unit) {
            object[] results = this.Invoke("AddApp", new object[] {
                        AppName,
                        Unit});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AddAppAsync(string AppName, string Unit) {
            this.AddAppAsync(AppName, Unit, null);
        }
        
        /// <remarks/>
        public void AddAppAsync(string AppName, string Unit, object userState) {
            if ((this.AddAppOperationCompleted == null)) {
                this.AddAppOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddAppOperationCompleted);
            }
            this.InvokeAsync("AddApp", new object[] {
                        AppName,
                        Unit}, this.AddAppOperationCompleted, userState);
        }
        
        private void OnAddAppOperationCompleted(object arg) {
            if ((this.AddAppCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddAppCompleted(this, new AddAppCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapDocumentMethod("http://jhy.org/GenUpdateInfo", RequestNamespace="http://jhy.org/", ResponseNamespace="http://jhy.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GenUpdateInfo(string AppName, string Unit, string NewVer, string UpdLog) {
            object[] results = this.Invoke("GenUpdateInfo", new object[] {
                        AppName,
                        Unit,
                        NewVer,
                        UpdLog});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GenUpdateInfoAsync(string AppName, string Unit, string NewVer, string UpdLog) {
            this.GenUpdateInfoAsync(AppName, Unit, NewVer, UpdLog, null);
        }
        
        /// <remarks/>
        public void GenUpdateInfoAsync(string AppName, string Unit, string NewVer, string UpdLog, object userState) {
            if ((this.GenUpdateInfoOperationCompleted == null)) {
                this.GenUpdateInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenUpdateInfoOperationCompleted);
            }
            this.InvokeAsync("GenUpdateInfo", new object[] {
                        AppName,
                        Unit,
                        NewVer,
                        UpdLog}, this.GenUpdateInfoOperationCompleted, userState);
        }
        
        private void OnGenUpdateInfoOperationCompleted(object arg) {
            if ((this.GenUpdateInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenUpdateInfoCompleted(this, new GenUpdateInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetAllUnitCompletedEventHandler(object sender, GetAllUnitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class GetAllUnitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllUnitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetAvailableUnitCompletedEventHandler(object sender, GetAvailableUnitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class GetAvailableUnitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAvailableUnitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetAppByUnitCompletedEventHandler(object sender, GetAppByUnitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class GetAppByUnitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAppByUnitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetAvailableAppByUnitCompletedEventHandler(object sender, GetAvailableAppByUnitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class GetAvailableAppByUnitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAvailableAppByUnitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetServerVersionCompletedEventHandler(object sender, GetServerVersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class GetServerVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetServerVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetFileUpdListCompletedEventHandler(object sender, GetFileUpdListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class GetFileUpdListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFileUpdListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ReqFileCompletedEventHandler(object sender, ReqFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class ReqFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReqFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ReqFileUrlCompletedEventHandler(object sender, ReqFileUrlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class ReqFileUrlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReqFileUrlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void DelAppFileCompletedEventHandler(object sender, DelAppFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class DelAppFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DelAppFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void AddAppCompletedEventHandler(object sender, AddAppCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class AddAppCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddAppCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GenUpdateInfoCompletedEventHandler(object sender, GenUpdateInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class GenUpdateInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenUpdateInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591